# Generated by Django 4.0.5 on 2023-06-11 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkoutExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('weight', models.FloatField(default=1)),
                ('count', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='GymWorkout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body_workout', models.CharField(max_length=20)),
                ('date', models.DateTimeField(blank=True)),
                ('exercises', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='myapi.workoutexercise')),
            ],
        ),
    ]
