# Generated by Django 4.0.5 on 2023-06-11 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0002_workoutexercise_gymworkout'),
    ]

    operations = [
        migrations.CreateModel(
            name='BodyMuscle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.RenameField(
            model_name='gymworkout',
            old_name='exercises',
            new_name='exercise',
        ),
        migrations.AddField(
            model_name='workoutexercise',
            name='body_muscle',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='myapi.bodymuscle'),
        ),
    ]
