# Generated by Django 4.0.5 on 2023-06-11 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0003_bodymuscle_rename_exercises_gymworkout_exercise_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('date', models.DateTimeField(blank=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='BodyMuscle',
            new_name='Muscle',
        ),
        migrations.RenameModel(
            old_name='WorkoutExercise',
            new_name='Exercise',
        ),
        migrations.DeleteModel(
            name='GymWorkout',
        ),
        migrations.AddField(
            model_name='workout',
            name='exercise',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='myapi.exercise'),
        ),
        migrations.AddField(
            model_name='program',
            name='workout',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='myapi.workout'),
        ),
    ]
