# Generated by Django 4.0.5 on 2023-06-11 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0006_alter_exercise_workout'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='workout',
        ),
    ]
