# Generated by Django 4.0.5 on 2023-06-11 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0007_remove_exercise_workout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='workout',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapi.workout'),
        ),
    ]
