# Generated by Django 4.0.5 on 2023-06-11 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0008_alter_program_workout'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='program',
            name='workout',
        ),
        migrations.AddField(
            model_name='exercise',
            name='workout',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapi.workout'),
        ),
        migrations.AddField(
            model_name='workout',
            name='workout',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapi.program'),
        ),
    ]
