# Generated by Django 4.0.5 on 2023-06-11 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0009_remove_program_workout_exercise_workout_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workout',
            old_name='workout',
            new_name='program',
        ),
    ]
