# Generated by Django 4.0.5 on 2023-06-11 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0010_rename_workout_workout_program'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='body_muscle',
        ),
        migrations.AddField(
            model_name='exercise',
            name='body_muscle',
            field=models.ManyToManyField(default=None, to='myapi.muscle'),
        ),
    ]
